// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace GUI_Test
{
	public partial class AMPathPopUpButton : NSButton
	{
		public AMPathPopUpButton (IntPtr handle) : base (handle)
		{
		}
	}
}
