// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace BloodPressureMeasurementMacApp
{
	public partial class AMPathPopUpButton : NSPopUpButton
	{
		public AMPathPopUpButton (IntPtr handle) : base (handle)
		{
		}
	}
}
